name: The Genbukan Harukaze Dojo
favicon: null
layout_spectrum: 0.17919
typography_spectrum: 0.7353210437577218
title: The Genbukan Harukaze Dojo/GaryGiamboiKyoshi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f6d8'
    - '#38532d'
    - '#000000'
    - '#f90000'
    - '#60b308'
  brandStrength: 0.3125
  lightness: 0.5286033372394741
  saturation: 0
  rhythmicContrast: 0.7271659141406417
purpose: []
