name: HarukazeDojo
favicon: null
layout_spectrum: 0.9313166888896376
typography_spectrum: 0.7353210437577218
title: The Genbukan Harukaze Dojo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5022981893271208
  lightness: 0.5286033372394741
  saturation: 0.1559569383971393
  rhythmicContrast: 0.7271659141406417
purpose: []
