name: The Genbukan Harukaze Dojo
favicon: null
layout_spectrum: 0.16354
typography_spectrum: 0.7353210437577218
title: The Genbukan Harukaze Dojo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#565100'
    - '#1f2e00'
    - '#7ebb24'
    - '#e9f581'
  brandStrength: 0.5022981893271208
  lightness: 0.5286033372394741
  saturation: 0.1559569383971393
  rhythmicContrast: 0.7271659141406417
purpose: []
